/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114814-ge4f5c2414b-20240411"
#endif /* AVUTIL_FFVERSION_H */
